version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - 6379

  rabbit:
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://rabbit:15672']
      interval: 30s
      timeout: 10s
      retries: 5
